name: Build Android NDK

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64]
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build make \
            autoconf automake libtool pkg-config texinfo gettext gperf \
            bison flex git xz-utils unzip nasm yasm python3 python3-pip python3-venv

      - name: Install pipx and Meson
        run: |
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          export PATH="$HOME/.local/bin:$PATH"
          pipx install meson

      - name: Install Android NDK (r29 beta4)
        run: |
          cd $HOME
          NDK_VERSION="r29-beta4"
          NDK_ZIP="android-ndk-${NDK_VERSION}-linux.zip"
          curl -LO https://dl.google.com/android/repository/${NDK_ZIP}
          unzip ${NDK_ZIP}

          echo "ANDROID_NDK_ROOT=$HOME/android-ndk-${NDK_VERSION}" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$HOME/android-ndk-${NDK_VERSION}" >> $GITHUB_ENV
          echo "ANDROID_NDK_ZIP=$HOME/${NDK_ZIP}" >> $GITHUB_ENV
          echo "ANDROID_NDK_VERSION=${NDK_VERSION}" >> $GITHUB_ENV


          TOOLCHAIN=$HOME/android-ndk-${NDK_VERSION}/toolchains/llvm/prebuilt/linux-x86_64/bin
          echo "$TOOLCHAIN" >> $GITHUB_PATH

      - name: Set ARCH
        run: echo "ARCH=${{ matrix.arch }}" >> $GITHUB_ENV

      - name: Build LLVM
        env:
          ARCH: ${{ matrix.arch }}
        run: bash ${{ github.workspace }}/build.sh

      - name: Upload NDK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: llvm-${{ matrix.arch }}
          path: |
            ${{ github.workspace }}/*.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Show collected files
        run: ls -R artifacts

      - name: Set build date
        run: echo "BUILD_DATE=$(date +'%Y-%m-%d %H:%M:%S %Z')" >> $GITHUB_ENV  

      - name: Create GitHub Release and upload ZIPs
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: android-ndk-${{ github.run_number }}
          name: "Android NDK Build ${{ github.run_number }}"
          body: |
            android-ndk build artifacts

            **Build Date:** ${{ env.BUILD_DATE }}
          files: artifacts/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
